# Book Settings
title: "AI Search Algorithms for Smart Mobility"
logo: images/sm.png
author: Alaa Khamis and Yinan Wang
copyright: "2021, Alaa Khamis and Yinan Wang"

#Jupyter Settings
execute:
  execute_notebooks: "cache"
  timeout: 600

only_build_toc_files: true


# HTML Settings
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: label
    html_theme: sphinx_book_theme
  extra_extensions:
  - sphinx_inline_tabs
bibtex_bibfiles:
- references.bib
  
#Interactive Settings
repository:
  url:  https://github.com/SmartMobilityAlgorithms/ECE1724
  branch: main

html:
  use_repository_button: true
